### ISSUE TITLE
project website

### ISSUE THREAD

**Issue by fstasel** [CankayaUniversity/ceng-407-408-2021-2022-TOBB-ANKARA-WOMEN-Entrepreneurs-Board-Mobile-Application-and-Web-Application#1]
Proje websiteniz okulun firewall'ı tarafından bloke ediliyor. Bilgi-işlem ile bu durumu konuşmanız gerekli.
S.

**Comment by umutsozerii** [comment]
Tamamdır hocam en kısa sürede görüşeceğiz

**Comment by umutsozerii** [comment]
Hocam, bilgi işlem ile görüştük. Bizim siteye özel wirefall kapandı tekrar kontrol edebilir misiniz acaba. 
Teşekkürler iyi günler.

**Comment by fstasel** [comment]
ok. açılıyor.
